name: mnist
user: ocdkube
parameters:
  class: training
  training:
    executor:
      choice: dkube
      buildfromproject: false
      dkube:
        framework:
          choice: pytorch
          details:
            version: 1.9
            image: 'ocdr/d3-datascience-pytorch-cpu:v1.9-10'
    datums:
      workspace:
        data:
          name: 'ocdkube:pt-example-0251285494'
          version: ''
        script: python model.py
      datasets:
        - name: 'ocdkube:mnist-pt'
          mountpath: /opt/dkube/input
      outputs:
        - name: 'ocdkube:mnist-pt'
          mountpath: /opt/dkube/output
    featuresets: {}
    tags: []
    hyperparams:
      customkv:
        - key: EPOCHS
          value: '1'
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
